### PR TITLE
Fixed the spelling to modify on line 449

### PR DESCRIPTION
**Pull request by BrendynDelage**
Fixed this

### CODE REVIEW

**Comment by StoneyJackson** [comment]
@BrendynDelage What issue # does this fix?

**Comment by StoneyJackson** [comment]
@BrendynDelage  You gave me the # for this pull request, not the initial issue. What issue # does this fix?

**Comment by BrendynDelage** [comment]
My bad this fixes the issue #55

**Comment by StoneyJackson** [comment]
Thanks!

**Pull request merged**
