### PR TITLE
Fixed the spelling to called on line 475

### PR DESCRIPTION
**Pull request by BrendynDelage**
fixed this

### CODE REVIEW

**Comment by StoneyJackson** [comment]
@BrendynDelage What issue # does this fix?

**Comment by BrendynDelage** [comment]
This fixes issue number #61

**Comment by StoneyJackson** [comment]
@BrendynDelage You gave me the # of this pull request not the # of the initial issue. What issue # does this fix?

**Comment by BrendynDelage** [comment]
this fixed issue #56

**Comment by StoneyJackson** [comment]
Thanks!

**Pull request merged**
