### PR TITLE
Changed rreptyop to property in line 298.

### PR DESCRIPTION
**Pull request by Eric51315**

### CODE REVIEW

**Comment by StoneyJackson** [comment]
@Eric51315 Which issue number does this fix?

**Comment by Eric51315** [comment]
This fixes issue #6

**Comment by StoneyJackson** [comment]
@Eric51315 There is a conflict. Please do the following.

1. Pull this repo's master into your local repo's master.
2. Merge your local master into your feature branch, fixing the conflict.
3. Push your feature branch to your fork which will update this PR.

**Comment by StoneyJackson** [comment]
@Eric51315 By closing this, I'm assuming you are abandoning this and you'll try another one later. You've completed two so far.

**Comment by Eric51315** [comment]
Yes, I was having trouble with the repository so I just wanted to start it over

**Pull request closed without merging**
