### PR TITLE
Resolves issue #3

### PR DESCRIPTION
**Pull request by kt348859**
- Resolves issue #3
  - Changed 'rdveeeic' to 'received'.

### CODE REVIEW

**Comment by StoneyJackson** [comment]
@kt348859 Please resolve the conflict.

I think you've chosen to fix 3 words on the same line. So once one is accepted the others will conflict. This is a great chance for you to show off your abilities to resolve conflicts!

**Comment by kt348859** [comment]
Conflict resolved. 

Strange that it brought up a conflict even though it is on separate lines. Then again it could be just soft-wrapping in the text editor.

**Comment by StoneyJackson** [comment]
This will be interesting. I can't wait to see what the graph looks like after I merge this.

**Comment by StoneyJackson** [comment]
Thanks!

**Pull request merged**
