### PR TITLE
Fix issue #80

### PR DESCRIPTION
**Pull request by theodorechoi123**

### CODE REVIEW

**Comment by theodorechoi123** [comment]
Fixed "emasn" on line 77 to "means"

**Comment by theodorechoi123** [comment]
Fixed "copyleft" on line 10 to "copyright"

**Comment by StoneyJackson** [comment]
@theodorechoi123 Your PR is conflicted. You'll need to resolve it before I can accept it. Also, in a comment to this PR include the issue number that this PR is fixing.

**Comment by theodorechoi123** [comment]
Resolved conflict and the issue number is #80

**Comment by StoneyJackson** [comment]
Thanks!

**Pull request merged**
