### PR TITLE
Changed the spelling to holders on line 362

### PR DESCRIPTION
**Pull request by BrendynDelage**
Fixed this

### CODE REVIEW

**Comment by StoneyJackson** [comment]
@BrendynDelage What issue # does this fix?

**Comment by BrendynDelage** [comment]
This fixes issue #59

**Comment by StoneyJackson** [comment]
Thanks!

**Comment by StoneyJackson** [comment]
@BrendynDelage You gave me the issue # of this pull-request, not the original. What issue # does this fix?

**Comment by BrendynDelage** [comment]
This fixed issue #54

**Pull request merged**
